# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

target 'PicData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'MBProgressHUD', '~> 1.1.0'  
  pod 'Masonry'
  pod 'MJExtension', '~> 3.0.13'
  pod 'SDWebImage', '~> 5.0'
  pod 'YYModel'
  pod 'YYCategories'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'XHWebImageAutoSize'
  pod 'Tiercel'
  pod 'TiercelObjCBridge'
  pod 'JQFMDB'
  pod 'SSZipArchive'
  pod 'IQKeyboardManager'
  # Pods for PicData

end
