# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

target 'PicData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry'
  pod 'MJExtension', '~> 3.0.13'
  pod 'SDWebImage', '~> 5.0'
  pod 'YYCategories'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'YYImage', :git => 'https://github.com/QiuYeHong90/YYImage.git'
  pod 'YBImageBrowser'
  pod 'WCDB'
  pod 'SSZipArchive'
  pod 'IQKeyboardManager'
  pod 'CWLateralSlide', '~> 1.6.3'
  pod 'PicDataSDK', :path => '../../PicDataSDK/PicDataSDK/Products'
  # Pods for PicData

end
